CREATE TABLE `mensagens_padroes` (
	`CODIGO` INT(11) NOT NULL AUTO_INCREMENT,
	`MENSAGEM` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`ETAPA` CHAR(1) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`CODIGO`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `mensagem` (
	`COD_MENSAGEM` INT(11) NOT NULL AUTO_INCREMENT,
	`CONTATO` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`TELEFONE` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`MENSAGEM` VARCHAR(10000) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`DATA_HORA_CRIACAO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`ATIVO` TINYINT(1) NULL DEFAULT NULL,
	`IDCONVERSA` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`TIPO_MENSAGEM` CHAR(1) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`DATA_ENVIO_RECEBIDO` TIMESTAMP NULL DEFAULT NULL,
	`ARQUIVO` BLOB NULL DEFAULT NULL,
	`DATA_PROCESSADO_API` TIMESTAMP NULL DEFAULT NULL,
	`STATUS` CHAR(2) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`COD_MENSAGEM`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=60
;

CREATE TABLE `campanha_mensagem` (
	`CODIGO` INT(11) NOT NULL AUTO_INCREMENT,
	`CODIGO_CAMPANHA_CLIENTE` INT(11) NOT NULL,
	`DATA_HORA_CRIACAO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`MENSAGEM` VARCHAR(10000) NOT NULL COLLATE 'latin1_swedish_ci',
	`STATUS` CHAR(2) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`EM_CONVERSACAO` VARCHAR(1) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`TELEFONE` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`IDCONVERSA` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	PRIMARY KEY (`CODIGO`) USING BTREE,
	INDEX `FK_CAMP_CLIENTE` (`CODIGO_CAMPANHA_CLIENTE`) USING BTREE,
	CONSTRAINT `FK_CAMP_CLIENTE` FOREIGN KEY (`CODIGO_CAMPANHA_CLIENTE`) REFERENCES `pim`.`campanhas_clientes` (`CODIGO`) ON UPDATE RESTRICT ON DELETE RESTRICT
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=8
;

CREATE TABLE `log_mensagem` (
	`CODIGO` INT(11) NOT NULL AUTO_INCREMENT,
	`DATA_HORA_CRIACAO_LOG` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`METODO` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`ERRO` VARCHAR(200) NOT NULL COLLATE 'latin1_swedish_ci',
	PRIMARY KEY (`CODIGO`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=8
;
